services:
  amazon-music:
    build: .
    image: orpheus-amazon-music:local
    stdin_open: true
    tty: true
    env_file:
      - config.env
    environment:
      AMZ_WVD_PATH: /run/secrets/amazon.wvd
    volumes:
      - ./config:/app/config
      - ./downloads:/app/downloads
      - ./device.wvd:/run/secrets/amazon.wvd:ro
